### ISSUE TITLE
Use simpler badge styling to match Windows 10 better

### ISSUE THREAD

**Issue by tooomm** [bstreiff/unread-badge#24]
Not exactly sure if there is an official styling or style guide regarding this...

But it looks like the addon mimics more the osx look.
Other apps, like Telegram, use a different and simpler styling to show badges in windows. It looks way more natural and better fits the other windows appearance in my opinion:

![telegram_unread_badge](https://user-images.githubusercontent.com/9874850/64978671-5c8e7c00-d8b6-11e9-91e3-8acbcc7d1b35.png)

**Comment by bstreiff** [comment]
Indeed, I was trying to copy the OS X notification badge style, since that's what I was accustomed to (having switched from OS X to Windows as my primary OS in ~2013). At the time, there wasn't a whole lot of consistency on what a notification badge looked like, so reusing OS X's style was consistently inconsistent.

The only thing I could find from Microsoft for a style guide on icon overlays is [this document](https://docs.microsoft.com/en-us/windows/win32/uxguide/winenv-taskbar), which still seems to be rather Windows 7-centric; given that Windows 7 will be falling out of extended support soon, and Windows 8 and Windows 10 adopt a flat look, it might be worth getting with the times.

I did find [this document on badge notifications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/badges), but it appears to only be for UWP apps.

For further reference, here's what the icons for Discord, Teams, and Slack show up as on my system:
![notification icons](https://user-images.githubusercontent.com/444845/64989740-c8132200-d893-11e9-9218-556a8758a05e.png)

- Discord is a light red circle with a white dot; there's no message count.
- Teams is a red circle; the font that is used doesn't have a horizontal bar at the base of the "1".
- Slack is a red circle; the font that is used uses a horizontal bar at the base of the "1". It also appears that the circle has a thin dark (maybe black?) outline.

**Comment by tooomm** [comment]
>Windows 10 adopt a flat look, it might be worth getting with the times.

Agreed!

I like the flat and more simple style with message count most.
Also, a red circle has already enough contrast to the Thunderbird logo itself. There is no additional outline needed.

Having a neutral "New Messages Available" badge (like Discord) in addition to the normal "Unread Count" badge would be a nice option.

**Comment by bstreiff** [comment]
Version 3.0.0 now includes multiple badge style options. The original OS X-inspired design is still present, but the new default is a flat red inspired by Teams, Slack, and Telegram which I'm treating as being the new "norm" for Windows notification badges.

![image](https://user-images.githubusercontent.com/444845/95664942-8776ee00-0b11-11eb-9cb5-76bf5717a9f5.png)
